import mongoose from 'mongoose';
import Place from './models/Place.js';

const places = [
  // Historical
  { name: 'Taj Mahal', city: 'Agra', state: 'Uttar Pradesh', location: 'Dharmapuri, Forest Colony', category: 'historical', entryFee: 250, childFee: 0, rating: 4.8, image: '🏛️', openingTime: '06:00', closingTime: '19:00', bestTime: 'Oct-Mar', duration: '2-3 hrs', description: 'One of the Seven Wonders of the World, this stunning white marble mausoleum was built by Emperor Shah Jahan in memory of his wife Mumtaz Mahal.' },
  { name: 'Red Fort', city: 'Delhi', state: 'Delhi', location: 'Chandni Chowk', category: 'historical', entryFee: 35, childFee: 0, rating: 4.5, image: '🏛️', openingTime: '07:00', closingTime: '18:00', bestTime: 'Nov-Feb', duration: '2-3 hrs', description: 'A historic fort in Delhi that served as the main residence of Mughal emperors for nearly 200 years.' },
  { name: 'Qutub Minar', city: 'Delhi', state: 'Delhi', location: 'Mehrauli', category: 'historical', entryFee: 30, childFee: 0, rating: 4.4, image: '🏛️', openingTime: '07:00', closingTime: '17:00', bestTime: 'Oct-Mar', duration: '1-2 hrs', description: 'The tallest brick minaret in the world, standing at 73 meters, built in 1193.' },
  { name: 'Hawa Mahal', city: 'Jaipur', state: 'Rajasthan', location: 'Badi Choupad', category: 'historical', entryFee: 50, childFee: 25, rating: 4.3, image: '🏛️', openingTime: '09:00', closingTime: '17:00', bestTime: 'Oct-Mar', duration: '1-2 hrs', description: 'The Palace of Winds with 953 small windows, built in 1799 for royal women to observe street festivals.' },
  { name: 'Amber Fort', city: 'Jaipur', state: 'Rajasthan', location: 'Amer', category: 'historical', entryFee: 100, childFee: 50, rating: 4.6, image: '🏰', openingTime: '08:00', closingTime: '18:00', bestTime: 'Oct-Mar', duration: '3-4 hrs', description: 'A majestic fort built with red sandstone and marble, overlooking Maota Lake.' },
  { name: 'Gateway of India', city: 'Mumbai', state: 'Maharashtra', location: 'Colaba', category: 'historical', entryFee: 0, childFee: 0, rating: 4.5, image: '🏛️', openingTime: '00:00', closingTime: '00:00', bestTime: 'Nov-Feb', duration: '1 hr', description: 'An iconic arch monument built in 1924 overlooking the Arabian Sea.' },
  { name: 'Charminar', city: 'Hyderabad', state: 'Telangana', location: 'Charminar Road', category: 'historical', entryFee: 25, childFee: 10, rating: 4.4, image: '🕌', openingTime: '09:00', closingTime: '17:30', bestTime: 'Oct-Mar', duration: '1-2 hrs', description: 'A monument and mosque built in 1591, with four grand arches and intricate minarets.' },
  { name: 'Mysore Palace', city: 'Mysore', state: 'Karnataka', location: 'Mysuru', category: 'historical', entryFee: 100, childFee: 50, rating: 4.7, image: '🏰', openingTime: '10:00', closingTime: '17:30', bestTime: 'Oct-Feb', duration: '2-3 hrs', description: 'A stunning royal palace known for its Indo-Saracenic architecture and grand illumination on Sundays.' },
  { name: 'Victoria Memorial', city: 'Kolkata', state: 'West Bengal', location: 'Maidan', category: 'historical', entryFee: 30, childFee: 10, rating: 4.5, image: '🏛️', openingTime: '10:00', closingTime: '17:00', bestTime: 'Nov-Feb', duration: '2-3 hrs', description: 'A magnificent white marble building dedicated to Queen Victoria, now a museum with 29 galleries.' },

  // Nature
  { name: 'Munnar Hill Station', city: 'Munnar', state: 'Kerala', location: 'Idukki District', category: 'nature', entryFee: 0, childFee: 0, rating: 4.7, image: '🌿', openingTime: '06:00', closingTime: '18:00', bestTime: 'Sep-Mar', duration: 'Full day', description: 'A breathtaking hill station known for tea plantations, rolling hills, and misty valleys.' },
  { name: 'Alleppey Backwaters', city: 'Alleppey', state: 'Kerala', location: 'Alappuzha', category: 'nature', entryFee: 0, childFee: 0, rating: 4.6, image: '🌊', openingTime: '06:00', closingTime: '18:00', bestTime: 'Nov-Feb', duration: 'Full day', description: 'Houseboat cruises through serene backwaters with palm-fringed canals and lush greenery.' },
  { name: 'Valley of Flowers', city: 'Joshimath', state: 'Uttarakhand', location: 'Chamoli District', category: 'nature', entryFee: 150, childFee: 75, rating: 4.8, image: '🌸', openingTime: '07:00', closingTime: '17:00', bestTime: 'Jul-Sep', duration: 'Full day', description: 'A UNESCO World Heritage site with endemic alpine flowers and stunning meadows.' },
  { name: 'Lonavala', city: 'Lonavala', state: 'Maharashtra', location: 'Pune District', category: 'nature', entryFee: 0, childFee: 0, rating: 4.3, image: '🌿', openingTime: '00:00', closingTime: '00:00', bestTime: 'Jun-Sep', duration: '1-2 days', description: 'A popular hill station known for its scenic valleys, waterfalls, and the famous Lonavala chikki.' },
  { name: 'Coorg', city: 'Coorg', state: 'Karnataka', location: 'Kodagu District', category: 'nature', entryFee: 0, childFee: 0, rating: 4.5, image: '🌿', openingTime: '00:00', closingTime: '00:00', bestTime: 'Oct-Mar', duration: '2-3 days', description: 'Scotland of India, known for coffee plantations, misty hills, and lush forests.' },
  { name: 'Chilika Lake', city: 'Puri', state: 'Odisha', location: 'Khordha District', category: 'nature', entryFee: 50, childFee: 25, rating: 4.3, image: '🌊', openingTime: '06:00', closingTime: '18:00', bestTime: 'Nov-Feb', duration: '3-4 hrs', description: 'Asia\'s largest brackish water lagoon and a paradise for birdwatchers.' },

  // Adventure
  { name: 'Rishikesh Rafting', city: 'Rishikesh', state: 'Uttarakhand', location: 'Triveni Ghat', category: 'adventure', entryFee: 500, childFee: 300, rating: 4.6, image: '🧗', openingTime: '06:00', closingTime: '17:00', bestTime: 'Sep-Jun', duration: '3-4 hrs', description: 'World-famous white water rafting on the Ganges with rapids ranging from Grade I to Grade IV.' },
  { name: 'Jim Corbett National Park', city: 'Ramnagar', state: 'Uttarakhand', location: 'Nainital District', category: 'adventure', entryFee: 600, childFee: 300, rating: 4.5, image: '🐅', openingTime: '06:00', closingTime: '11:30', bestTime: 'Nov-Jun', duration: '3-4 hrs', description: 'India\'s first national park, renowned for its Bengal tiger population and rich biodiversity.' },
  { name: 'Paragliding in Bir Billing', city: 'Bir', state: 'Himachal Pradesh', location: 'Baijnath', category: 'adventure', entryFee: 3500, childFee: 0, rating: 4.7, image: '🪂', openingTime: '06:00', closingTime: '17:00', bestTime: 'Mar-Jun, Sep-Nov', duration: '30-45 min', description: 'The world\'s second highest paragliding site with stunning Himalayan views.' },
  { name: 'Scuba Diving in Andaman', city: 'Port Blair', state: 'Andaman & Nicobar', location: 'Havelock Island', category: 'adventure', entryFee: 3500, childFee: 2500, rating: 4.8, image: '🤿', openingTime: '06:00', closingTime: '15:00', bestTime: 'Nov-Apr', duration: '3-4 hrs', description: 'Explore vibrant coral reefs and marine life in crystal clear waters.' },

  // Religious
  { name: 'Golden Temple', city: 'Amritsar', state: 'Punjab', location: 'Amritsar', category: 'religious', entryFee: 0, childFee: 0, rating: 4.9, image: '🛕', openingTime: '04:00', closingTime: '22:00', bestTime: 'Oct-Mar', duration: '2-3 hrs', description: 'The holiest Gurdwara of Sikhism, covered in gold leaf with a sacred pool surrounding it.' },
  { name: 'Varanasi Ghats', city: 'Varanasi', state: 'Uttar Pradesh', location: 'Dashashwamedh Ghat', category: 'religious', entryFee: 0, childFee: 0, rating: 4.7, image: '🛕', openingTime: '05:00', closingTime: '21:00', bestTime: 'Nov-Mar', duration: '2-3 hrs', description: 'Ancient ghats along the Ganges where pilgrims perform rituals and the famous Ganga Aarti.' },
  { name: 'Tirupati Balaji Temple', city: 'Tirupati', state: 'Andhra Pradesh', location: 'Tirumala', category: 'religious', entryFee: 0, childFee: 0, rating: 4.8, image: '🛕', openingTime: '03:00', closingTime: '21:00', bestTime: 'Sep-Feb', duration: '3-5 hrs', description: 'One of the richest and most visited temples in the world, dedicated to Lord Venkateswara.' },
  { name: 'Somnath Temple', city: 'Somnath', state: 'Gujarat', location: 'Veraval', category: 'religious', entryFee: 0, childFee: 0, rating: 4.5, image: '🛕', openingTime: '06:00', closingTime: '21:00', bestTime: 'Oct-Mar', duration: '1-2 hrs', description: 'One of the 12 Jyotirlinga shrines of Lord Shiva, located on the Arabian Sea coast.' },
  { name: 'Bodh Gaya', city: 'Bodh Gaya', state: 'Bihar', location: 'Gaya District', category: 'religious', entryFee: 0, childFee: 0, rating: 4.6, image: '🛕', openingTime: '05:00', closingTime: '21:00', bestTime: 'Nov-Feb', duration: '2-3 hrs', description: 'The place where Buddha attained enlightenment under the Bodhi tree, a UNESCO World Heritage site.' },

  // Beaches
  { name: 'Baga Beach', city: 'Goa', state: 'Goa', location: 'Calangute', category: 'beach', entryFee: 0, childFee: 0, rating: 4.4, image: '🏖️', openingTime: '00:00', closingTime: '00:00', bestTime: 'Nov-Mar', duration: 'Full day', description: 'Goa\'s most popular beach with water sports, shacks, and vibrant nightlife.' },
  { name: 'Radhanagar Beach', city: 'Havelock', state: 'Andaman & Nicobar', location: 'Swaraj Dweep', category: 'beach', entryFee: 0, childFee: 0, rating: 4.7, image: '🏖️', openingTime: '06:00', closingTime: '17:00', bestTime: 'Nov-Apr', duration: 'Full day', description: 'Asia\'s best beach with pristine white sand and turquoise waters.' },
  { name: 'Marina Beach', city: 'Chennai', state: 'Tamil Nadu', location: 'Santhome', category: 'beach', entryFee: 0, childFee: 0, rating: 4.2, image: '🏖️', openingTime: '04:00', closingTime: '23:00', bestTime: 'Nov-Feb', duration: '1-2 hrs', description: 'The world\'s second longest urban beach stretching 13 km along the Bay of Bengal.' },
  { name: 'Kovalam Beach', city: 'Kovalam', state: 'Kerala', location: 'Thiruvananthapuram', category: 'beach', entryFee: 0, childFee: 0, rating: 4.3, image: '🏖️', openingTime: '06:00', closingTime: '18:00', bestTime: 'Sep-Mar', duration: 'Full day', description: 'A crescent-shaped beach with lighthouse views and Ayurvedic massage centers.' },
  { name: 'Gokarna Beach', city: 'Gokarna', state: 'Karnataka', location: 'Uttara Kannada', category: 'beach', entryFee: 0, childFee: 0, rating: 4.4, image: '🏖️', openingTime: '06:00', closingTime: '19:00', bestTime: 'Oct-Mar', duration: 'Full day', description: 'A serene pilgrimage town with beautiful, uncrowded beaches.' },

  // Hill Stations
  { name: 'Shimla', city: 'Shimla', state: 'Himachal Pradesh', location: 'Mall Road', category: 'hill_station', entryFee: 0, childFee: 0, rating: 4.4, image: '🏔️', openingTime: '00:00', closingTime: '00:00', bestTime: 'Mar-Jun, Dec-Feb', duration: '2-3 days', description: 'The summer capital of British India, known for its colonial architecture and scenic beauty.' },
  { name: 'Manali', city: 'Manali', state: 'Himachal Pradesh', location: 'Kullu District', category: 'hill_station', entryFee: 0, childFee: 0, rating: 4.5, image: '🏔️', openingTime: '00:00', closingTime: '00:00', bestTime: 'Oct-Jun', duration: '3-4 days', description: 'A picturesque hill station in the Himalayas, gateway to Ladakh and known for snow-capped peaks.' },
  { name: 'Darjeeling', city: 'Darjeeling', state: 'West Bengal', location: 'Darjeeling District', category: 'hill_station', entryFee: 0, childFee: 0, rating: 4.4, image: '🏔️', openingTime: '00:00', closingTime: '00:00', bestTime: 'Mar-May, Oct-Dec', duration: '2-3 days', description: 'Queen of the Hills, famous for tea gardens, toy train, and views of Kanchenjunga.' },
  { name: 'Ooty', city: 'Ooty', state: 'Tamil Nadu', location: 'Nilgiris District', category: 'hill_station', entryFee: 0, childFee: 0, rating: 4.3, image: '🏔️', openingTime: '00:00', closingTime: '00:00', bestTime: 'Oct-Jun', duration: '2-3 days', description: 'Queen of Hill Stations in South India, with botanical gardens and a lovely lake.' },
  { name: 'Gangtok', city: 'Gangtok', state: 'Sikkim', location: 'East Sikkim', category: 'hill_station', entryFee: 0, childFee: 0, rating: 4.6, image: '🏔️', openingTime: '00:00', closingTime: '00:00', bestTime: 'Mar-May, Oct-Dec', duration: '3-4 days', description: 'A Buddhist monastery town in the Himalayas with panoramic mountain views.' },

  // Cultural
  { name: 'Khajuraho Temples', city: 'Khajuraho', state: 'Madhya Pradesh', location: 'Chhatarpur District', category: 'cultural', entryFee: 40, childFee: 0, rating: 4.5, image: '🎭', openingTime: '06:00', closingTime: '18:00', bestTime: 'Oct-Mar', duration: '3-4 hrs', description: 'UNESCO World Heritage site famous for its stunning Nagara-style temples with intricate erotic sculptures.' },
  { name: 'Hampi Ruins', city: 'Hampi', state: 'Karnataka', location: 'Bellary District', category: 'cultural', entryFee: 30, childFee: 0, rating: 4.6, image: '🎭', openingTime: '06:00', closingTime: '18:00', bestTime: 'Nov-Feb', duration: 'Full day', description: 'The ruins of the Vijayanagara Empire, a UNESCO World Heritage site with stunning stone architecture.' },
  { name: 'Ajanta & Ellora Caves', city: 'Aurangabad', state: 'Maharashtra', location: 'Sambhajinagar', category: 'cultural', entryFee: 40, childFee: 0, rating: 4.7, image: '🎭', openingTime: '06:00', closingTime: '17:30', bestTime: 'Oct-Mar', duration: '4-5 hrs', description: 'Ancient Buddhist, Hindu and Jain rock-cut cave monuments dating back to 2nd century BCE.' },
  { name: 'Konark Sun Temple', city: 'Konark', state: 'Odisha', location: 'Puri District', category: 'cultural', entryFee: 40, childFee: 0, rating: 4.5, image: '🎭', openingTime: '06:00', closingTime: '18:00', bestTime: 'Oct-Mar', duration: '2-3 hrs', description: 'A 13th century Sun Temple shaped like a massive chariot with intricate stone carvings.' },
  { name: 'Fatehpur Sikri', city: 'Agra', state: 'Uttar Pradesh', location: 'Fatehpur Sikri', category: 'cultural', entryFee: 35, childFee: 0, rating: 4.3, image: '🎭', openingTime: '06:00', closingTime: '18:00', bestTime: 'Oct-Mar', duration: '3-4 hrs', description: 'A UNESCO World Heritage city built by Emperor Akbar with stunning Mughal architecture.' },

  // Amusement
  { name: 'Wonderla Amusement Park', city: 'Bangalore', state: 'Karnataka', location: 'Mysore Road', category: 'amusement', entryFee: 999, childFee: 750, rating: 4.3, image: '🎡', openingTime: '10:00', closingTime: '18:00', bestTime: 'Oct-Feb', duration: 'Full day', description: 'One of India\'s largest amusement parks with thrilling rides and water attractions.' },
  { name: 'Imagica Theme Park', city: 'Mumbai', state: 'Maharashtra', location: 'Khopoli-Pali Road', category: 'amusement', entryFee: 1099, childFee: 799, rating: 4.2, image: '🎡', openingTime: '10:00', closingTime: '19:00', bestTime: 'Nov-Feb', duration: 'Full day', description: 'A world-class theme park with themed zones, roller coasters, and water park.' },
  { name: 'Science City Kolkata', city: 'Kolkata', state: 'West Bengal', location: 'Topsia', category: 'museum', entryFee: 50, childFee: 30, rating: 4.1, image: '🔬', openingTime: '09:00', closingTime: '20:00', bestTime: 'All year', duration: '3-4 hrs', description: 'The largest science center in the Indian subcontinent with interactive exhibits.' },
  { name: 'Nehru Planetarium', city: 'Mumbai', state: 'Maharashtra', location: 'Worli', category: 'museum', entryFee: 100, childFee: 50, rating: 4.2, image: '🔭', openingTime: '10:00', closingTime: '18:00', bestTime: 'All year', duration: '2-3 hrs', description: 'A fascinating planetarium with immersive shows about astronomy and space exploration.' },
  { name: 'Salar Jung Museum', city: 'Hyderabad', state: 'Telangana', location: 'Afzal Gunj', category: 'museum', entryFee: 20, childFee: 10, rating: 4.3, image: '🏛️', openingTime: '10:00', closingTime: '17:00', bestTime: 'All year', duration: '3-4 hrs', description: 'One of India\'s three national museums with a collection of over 43,000 art objects.' },
  { name: 'EsselWorld', city: 'Mumbai', state: 'Maharashtra', location: 'Gorai', category: 'amusement', entryFee: 850, childFee: 650, rating: 4.1, image: '🎡', openingTime: '10:00', closingTime: '18:00', bestTime: 'Nov-Feb', duration: 'Full day', description: 'India\'s largest amusement park with over 50 rides and attractions.' },
  { name: 'Ramoji Film City', city: 'Hyderabad', state: 'Telangana', location: 'Abdullapurmet', category: 'amusement', entryFee: 1150, childFee: 950, rating: 4.3, image: '🎬', openingTime: '09:00', closingTime: '17:30', bestTime: 'Oct-Mar', duration: 'Full day', description: 'The world\'s largest film studio complex with themed attractions and behind-the-scenes tours.' },

  // More places
  { name: 'Ladakh', city: 'Leh', state: 'Ladakh', location: 'Leh District', category: 'adventure', entryFee: 0, childFee: 0, rating: 4.8, image: '🏔️', openingTime: '00:00', closingTime: '00:00', bestTime: 'Jun-Sep', duration: '5-7 days', description: 'A high-altitude desert with stunning landscapes, Buddhist monasteries, and thrilling mountain passes.' },
  { name: 'Andaman Islands', city: 'Port Blair', state: 'Andaman & Nicobar', location: 'Port Blair', category: 'beach', entryFee: 0, childFee: 0, rating: 4.6, image: '🏖️', openingTime: '00:00', closingTime: '00:00', bestTime: 'Nov-Apr', duration: '4-5 days', description: 'A tropical paradise with pristine beaches, coral reefs, and historic cellular jail.' },
  { name: 'Kerala Houseboat', city: 'Kumarakom', state: 'Kerala', location: 'Kottayam District', category: 'nature', entryFee: 5000, childFee: 2500, rating: 4.7, image: '🚢', openingTime: '12:00', closingTime: '09:00', bestTime: 'Nov-Feb', duration: '1-2 nights', description: 'Traditional houseboat cruise through the serene backwaters of Kerala with delicious cuisine.' },
  { name: 'Ranthambore National Park', city: 'Sawai Madhopur', state: 'Rajasthan', location: 'Ranthambore Road', category: 'adventure', entryFee: 500, childFee: 250, rating: 4.5, image: '🐅', openingTime: '06:00', closingTime: '18:00', bestTime: 'Oct-Jun', duration: '3-4 hrs', description: 'Famous tiger reserve with a 10th-century fort and abundant wildlife.' },
  { name: 'Dal Lake', city: 'Srinagar', state: 'Jammu & Kashmir', location: 'Srinagar', category: 'nature', entryFee: 0, childFee: 0, rating: 4.6, image: '🌊', openingTime: '06:00', closingTime: '19:00', bestTime: 'Apr-Oct', duration: '2-3 hrs', description: 'The jewel of Kashmir with shikara rides, floating gardens, and houseboats.' },
];

async function seed() {
  try {
    await mongoose.connect('mongodb://localhost:27017/ticket-booking');
    console.log('Connected to MongoDB');
    
    await Place.deleteMany({});
    console.log('Cleared existing places');
    
    await Place.insertMany(places);
    console.log(`Seeded ${places.length} places successfully`);
    
    await mongoose.disconnect();
    console.log('Done!');
  } catch (e) {
    console.error('Error:', e.message);
    process.exit(1);
  }
}

seed();
